### ISSUE TITLE
 Warning: explode() expects parameter 2 to be string, array given

### ISSUE THREAD

**Issue by tomjn** [humanmade/memcache-object-cache#14]
```
 Warning: explode() expects parameter 2 to be string, array given in /srv/www/tomjn.com/htdocs/wp-content/object-cache.php on line 619
```

I'm encountering this in PHP 7.2 while using this, I've ran `wp cache flush` to try and clear things out but with no luck, continuing to debug

**Comment by rmccue** [comment]
IIRC, this means you have the memcache config variable in the wrong format; the array format is used for https://github.com/humanmade/wordpress-pecl-memcached-object-cache instead.

**Comment by tomjn** [comment]
Problem identified!

In a previous version used, you could define your memcached server as an array where each item was an array with the server then the port, I had to change this for it to work
